# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb_data:/bitnami/mariadb
  moodle:
    #image: docker.io/bitnami/moodle:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES=de_DE.UTF-8 UTF-8

    ports:
      - '9080:8080'
      - '9443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/moodle_data:/bitnami/moodle
      - ./data/moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
#  webserver:
#    depends_on:
#      - moodle
#    image: nginx:latest
#    ports:
#      - 10080:80
#      - 10443:443
#    restart: always
#    volumes:
#      - ./nginx/conf/:/etc/nginx/conf.d/:ro
#      - ./data/certbot/www:/var/www/certbot/:ro
#      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./data/certbot/www/:/var/www/certbot/:rw
#      - ./data/certbot/conf/:/etc/letsencrypt/:rw