# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb:/bitnami/mariadb # <-- This is the data directory, all database files are stored here. Whatever you do, DO NOT DELETE THIS DIRECTORY
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/moodle_installation:/bitnami/moodle # <-- This is the installation directory, all php files are stored here
      - ./data/moodle_userdata:/bitnami/moodledata # <-- This is the data directory, all user data is stored here. Whatever you do, DO NOT DELETE THIS DIRECTORY
    depends_on:
      - mariadb
  webserver:
    depends_on:
      - moodle
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro # <-- In this directory lives the nginx configuration file, so we can track it via git
      - ./data/certbot/www:/var/www/certbot/:ro # <-- This is the directory where certbot will store the challenge files
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro # <-- This is the directory where certbot will store the certificates
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/:rw # <-- This is the directory where certbot will store the challenge files
      - ./data/certbot/conf/:/etc/letsencrypt/:rw # <-- This is the directory where certbot will store the certificates